### ISSUE TITLE
Can this work with a chromecast ?

### ISSUE THREAD

**Issue by LUEshi42** [TheGreatSkeeve/Infinite-Plex-Autoplay#1]
most chromecast stuff nowadays only wants to work when done through chrome, think this "patch" could work with a chromecast device ?

**Comment by TheGreatSkeeve** [comment]
It doesn't, no.  I got tunnel vision when I was writing it, and focused on solving one specific use case just to show it could be done haha.  That being said, I believe Python has a library for Chromecasts, so I believe I could add the functionality.  I need to touch up this bad boy anyway, this is like one of the first things I ever wrote haha.
